export const ActionsTypes = {
  'GET_ADVERTISIMENT_REQUEST': 'GET_ADVERTISIMENT_REQUEST',
  'GET_ADVERTISIMENT_SUCCESS': 'GET_ADVERTISIMENT_SUCCESS',
  'GET_ADVERTISIMENT_FAILURE': 'GET_ADVERTISIMENT_FAILURE',
  'GET_ADVERTISIMENTS_REQUEST': 'GET_ADVERTISIMENTS_REQUEST',
  'GET_ADVERTISIMENTS_SUCCESS': 'GET_ADVERTISIMENTS_SUCCESS',
  'GET_ADVERTISIMENTS_FAILURE': 'GET_ADVERTISIMENTS_FAILURE',
  'CREATE_ADVERTISIMENT_REQUEST': 'CREATE_ADVERTISIMENT_REQUEST',
  'CREATE_ADVERTISIMENT_SUCCESS': 'CREATE_ADVERTISIMENT_SUCCESS',
  'CREATE_ADVERTISIMENT_FAILURE': 'CREATE_ADVERTISIMENT_FAILURE',
  'UPDATE_ADVERTISIMENT_REQUEST': 'UPDATE_ADVERTISIMENT_REQUEST',
  'UPDATE_ADVERTISIMENT_SUCCESS': 'UPDATE_ADVERTISIMENT_SUCCESS',
  'UPDATE_ADVERTISIMENT_FAILURE': 'UPDATE_ADVERTISIMENT_FAILURE',
  'SET_LIST_TYPE': 'SET_LIST_TYPE',
  'SET_PAGE': 'SET_PAGE'
}

export const apiUrl = 'http://localhost:3000'
